[WIP] Added the developer guide to writing a new connector.
infinyon/fluvio-website pull request #203
Opened 2021-11-11 15:02 UTC by simlay

Rendered: ![image](https://user-images.githubusercontent.com/1163510/141320110-c8d10b22-946b-4d6c-9078-e5bbcc14e1c8.png)

2021-11-11 15:37 UTC, ajhunyady commented
A couple of suggestions:
* describe the sections in the connector configuration file.
* what's the syntax used to generate this configuration file. Is it https://json-schema.org/specification.html ?

2021-11-11 15:41 UTC, nicholastmosher commented on content/connectors/developer-guide/overview.md
> +    "schema": {
I would recommend showing the command that printed this output, e.g.

```
$ test-connector metadata
{ ... }
```

that way people have more context on the fact that it's a subcommand to their connector executable

2021-11-29 21:25 UTC, nicholastmosher requested changes
Looks good except for a few typos. I was also wondering if you could move `developer-guide/_index.md.hidden` back to `developer-guide/_index.md` so that the proper sidebar header appears.

2021-11-29 21:25 UTC, nicholastmosher commented on content/connectors/developer-guide/overview.md
> +follow a few conventions and will gladly add and maintain a connector in our
`s/and will gladly/and we will gladly/`

2021-11-29 21:25 UTC, nicholastmosher commented on content/connectors/developer-guide/overview.md
> +To do so you'll need to following steps:
`s/need to following/need to do the following/`

2021-11-29 21:25 UTC, nicholastmosher commented on content/connectors/developer-guide/overview.md
> +static library, we'd ask you to have `build` make rule which handles these
how about

> we'd ask you to have a `make build` rule

2021-11-29 22:38 UTC, nicholastmosher approved these changes
Looks good!

2021-11-30 18:12 UTC, merged