feat: provide http sink documentation
infinyon/fluvio-website pull request #561
Opened 2023-04-27 18:24 UTC by EstebanBorai

2023-04-28 03:41 UTC, ajhunyady approved these changes
LGTM

2023-04-28 03:42 UTC, ajhunyady commented
thought this looks like it's still in Draft.

2023-05-02 21:36 UTC, EstebanBorai commented
Hi @ajhunyady! I just updated missing bits from docs with latest updates!

2023-05-02 22:00 UTC, morenol requested changes

2023-05-02 22:00 UTC, morenol commented on embeds/connectors/outbound/http.md
We use to keep this file on sync with connector readme in the repo. Could you update this first there?

2023-05-02 22:04 UTC, EstebanBorai commented on embeds/connectors/outbound/http.md
Sure thing!

2023-05-02 22:53 UTC, EstebanBorai commented
Copying manually from https://github.com/infinyon/http-sink-connector/pull/23

2023-05-02 22:56 UTC, morenol approved these changes

2023-05-03 00:50 UTC, ajhunyady approved these changes
Looks good.

2023-05-03 01:48 UTC, EstebanBorai commented
bors r+

2023-05-03 01:55 UTC, closed without merging